external-dns: {}
cert-manager:
  installCRDs: false
# Values are here because the values passed from appset parameters are kinda crappy when values are in charts/values.yaml
ingress-nginx:
  controller:
    service:
      externalTrafficPolicy: Local
      external:
        enabled: false