# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: addons
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"
# spec:
#   generators:
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 - addonChart: reloader
#           - clusters: {}
#   template:
#     metadata:
#       name: "{{name}}-{{addonChart}}"
#     spec:
#       project: default
#       source:
#         helm:
#           valueFiles:
#             - "../../clusters/common/system-values.yaml"
#           parameters:
#           - name: "nginx.controller.metrics.serviceMonitor.additionalLabels.suite"
#             value: "{{name}}"
#           - name: "nginx.controller.metrics.serviceMonitor.metricRelabelings.replacement"
#             value: "{{name}}"
#         repoURL: "https://github.com/lovelinuxalot/argo-gitops"
#         path: charts/{{addonChart}}
#         targetRevision: HEAD
#       destination:
#         namespace: "default"
#         name: "{{name}}"
#       syncPolicy:
#         automated: {}
#         syncOptions:
#           - CreateNamespace=true
#           - ServerSideApply=true # Big CRDs.
