# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: addons
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"
# spec:
#   generators:
#     # - matrix:
#     #     generators:
#     #       - list:
#     #           elements: # from /charts/
#     #             - addonChart: external-secrets
#     #             - addonChart: kyverno
#     #       - clusters:
#     #           selector:
#     #             matchExpressions:
#     #               - {
#     #                   key: "a52/cluster-name",
#     #                   operator: NotIn,
#     #                   values: [in-cluster],
#     #                 }
#     - matrix:
#         generators:
#           - list:
#               elements:
#                 # - addonChart: reloader
#                 # - addonChart: external-dns
#                 # - addonChart: cert-manager
#                 - addonChart: ingress-nginx

#           - clusters: {}
#     # - matrix:
#     #     generators:
#     #       - list:
#     #           elements:
#     #       - clusters:
#     #           selector:
#     #             matchExpressions:
#     #               - {
#     #                   key: "a52/cluster-name",
#     #                   operator: In,
#     #                   values: [cb],
#     #                 }
#     # - list:
#     #     elements:
#     #       - addonChart: reloader
#     #       - addonChart: external-dns

#   template:
#     metadata:
#       name: "{{name}}-{{addonChart}}"
#     spec:
#       project: default
#       source:
#         helm:
#           valueFiles:
#             - "../../clusters/common/addons-values.yaml"
#           parameters:
#           - name: "nginx.controller.metrics.serviceMonitor.additionalLabels.suite"
#             value: "{{name}}"
#           - name: "nginx.controller.metrics.serviceMonitor.metricRelabelings.replacement"
#             value: "{{name}}"
#         repoURL: "https://github.com/lovelinuxalot/argo-gitops"
#         path: charts/{{addonChart}}
#         targetRevision: HEAD
#       destination:
#         namespace: "default"
#         name: "{{name}}"
#       syncPolicy:
#         automated: {}
#         syncOptions:
#           - CreateNamespace=true
#           - ServerSideApply=true # Big CRDs.
