apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchExpressions:
                        - {
                            key: "a52-filia/cluster-name",
                            operator: In,
                            values: [cb, fsp],
                          }
                - git:
                    repoURL: https://github.com/lovelinuxalot/argo-gitops
                    revision: HEAD
                    files:
                    - path: environments/{{.metadata.labels.env}}/versions.yaml
          - git:
              repoURL: https://github.com/lovelinuxalot/argo-gitops
              revision: HEAD
              files:
              - path: releases/*.yaml

  template:
    metadata:
      name: "{{.name}}-ingress-nginx"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - "values.yaml"
            - "../../clusters/{{.name}}/ingress-values.yaml"
            - "../../environments/{{.path.basename}}/{{.name}}/ingress-values.yaml"
          parameters:
            - name: ingress-nginx.controller.image.tag
              value: "{{ .versions.ingress_nginx }}"
            - name: release_version
              value: "{{ .versions }}"
        repoURL: "https://github.com/lovelinuxalot/argo-gitops"
        path: charts/ingress-nginx
        targetRevision: HEAD
      destination:
        namespace: "default"
        name: "{{.name}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
          - ApplyOutOfSyncOnly=true

