apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - matrix:
        generators:
          # - list:
          #     elements:
          #       # - addonChart: external-dns
          #       # - addonChart: cert-manager
          #       - addonChart: ingress-nginx
          - git:
              repoURL: https://github.com/lovelinuxalot/argo-gitops
              revision: HEAD
              files:
              - path: environments/*/versions.yaml
          - clusters:
              selector:
                matchExpressions:
                  - {
                      key: "a52-filia/cluster-name",
                      operator: In,
                      values: [cb],
                    }

  template:
    metadata:
      name: "{{name}}-ingress-nginx"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - "values.yaml"
            - "../../clusters/{{name}}/ingress-values.yaml"
            - "../../environments/{{path.basename}}/{{name}}/ingress-values.yaml"
            - "../../releases/{{ versions.release }}.yaml"
          parameters:
            - name: version
              value: "{{.versions.ingress-nginx}}"
        repoURL: "https://github.com/lovelinuxalot/argo-gitops"
        path: charts/ingress-nginx
        targetRevision: HEAD
      destination:
        namespace: "default"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
