apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - addonChart: prometheus
          - clusters: {}
  template:
    metadata:
      name: "{{name}}-{{addonChart}}"
    annotations:
      argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      source:
        helm:
          parameters:
          - name: "prometheus.prometheus.prometheusSpec.serviceMonitor.externalLabels.cluster"
            value: "{{name}}"
          valueFiles:
            - "../../clusters/common/addons-values.yaml"
        repoURL: "https://github.com/lovelinuxalot/argo-gitops"
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: "monitoring"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
