apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - addonChart: reloader
          - clusters: {}
  template:
    metadata:
      name: "{{name}}-{{addonChart}}"
    spec:
      project: default
      source:
        helm:
          valuesObject:
            {{ toYaml .Values.system.reloader | nindent 12 }}
          parameters:
        repoURL: "https://github.com/lovelinuxalot/argo-gitops"
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: "default"
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
