---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: "{{ .Values.cluster }}"
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.replicas }}
  persistence:
    {{ toYaml .Values.persistence | nindent 4}}
  rabbitmq:
    additionalPlugins:
      - rabbitmq_shovel
      - rabbitmq_shovel_management
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: "{{ .Values.vhost }}"
  namespace: "{{ .Values.namespace }}"
spec:
  name: "{{ .Values.namespace }}"
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: "{{ .Values.topic }}"
  namespace: "{{ .Values.namespace }}"
spec:
  name: "{{ .Values.topic }}"
  type: fanout
  autoDelete: false
  durable: false
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
  vhost: "{{ .Values.namespace }}"
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: "{{ .Values.subscription }}"
  namespace: "{{ .Values.namespace }}"
spec:
  name: "{{ .Values.subscription }}"
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
  vhost: "{{ .Values.namespace }}"
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: subsribe-{{ .Values.subscription }}-to-{{ .Values.topic }}
  namespace: "{{ .Values.namespace }}"
spec:
  source: "{{ .Values.topic }}"
  destination: "{{ .Values.subscription }}"
  destinationType: queue
  routingKey: "#"
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
  vhost: "{{ .Values.namespace }}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.userSecret }}"
data:
  "username": "{{ .Values.username | b64enc }}"
  "password": "{{ .Values.password | b64enc }}"
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: "{{ .Values.username }}"
  namespace: "{{ .Values.namespace }}"
spec:
  tags: []
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
  importCredentialsSecret:
    name: "{{ .Values.userSecret }}"
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: "{{ .Values.username }}"
  namespace: "{{ .Values.namespace }}"
spec:
  user: "{{ .Values.username }}"
  permissions:
    read: "{{  .Values.readPermissions }}"
    write: "{{ .Values.writePermissions }}"
    configure: "{{ .Values.configurePermissions }}"
  rabbitmqClusterReference:
    name: "{{ .Values.cluster }}"
    namespace: "{{ .Values.namespace }}"
  vhost: "{{ .Values.namespace }}"