rabbitmq:
  clusterOperator:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
  msgTopologyOperator:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false

cluster: "default"
namespace: "default"
replicas: 1
persistence: {}

vhosts:
- name: default
  exchanges:
  - name: default-topic
    autoDelete: false
    durable: false
    type: fanout
  queues:
  - name: default-queue
    autoDelete: false
    durable: false
  bindings:
  - source: default-topic
    destination: default-queue
    destinationType: queue
    routingKey: "#"
  users:
  - username: user
    password: password
    readPermissions: ".*"
    writePermissions: ".*"
    configurePermissions: ".*"


