# external-secrets: {}
# kyverno: {}
reloader:
  podMonitor:
    enabled: true
external-dns: {}
cert-manager:
  installCRDs: false
prometheus:
  namespaceOverride: "monitoring"
  fullnameOverride: "prometheus"
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  prometheus:
    enabled: true
    service:
      type: LoadBalancer
      port: 9090
      targetPort: 9090
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ingress-internal"
    prometheusSpec:
      portName: http
      resources:
        limits:
          memory: "2500Mi"
        requests:
          memory: "400Mi"
      ruleSelector:
        matchLabels: {}
      serviceMonitorSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: "16Gi"
      externalLabels:
        # cluster: "{{ suite_k8s_namespace }}"
  prometheus-node-exporter:
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

