# external-secrets: {}
# kyverno: {}
reloader:
  podMonitor:
    enabled: true
external-dns: {}
cert-manager:
  installCRDs: false
prometheus:
  namespaceOverride: "monitoring"
  fullnameOverride: "prometheus"
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  prometheus:
    enabled: true
    service:
      type: LoadBalancer
      port: 9090
      targetPort: 9090
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ingress-internal"
    prometheusSpec:
      portName: http
      resources:
        limits:
          memory: "2500Mi"
        requests:
          memory: "400Mi"
      ruleSelector:
        matchLabels: {}
      serviceMonitorSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: "16Gi"
      externalLabels:
        # cluster: "{{ suite_k8s_namespace }}"
  prometheus-node-exporter:
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
ingress-nginx:
  rbac:
    create: true
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    ingressClassResource:
      name: public
    replicaCount: 1
    service:
      externalTrafficPolicy: Local
      external:
        enabled: true
      annotations:
        "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path": "/healthz"
        # Azure seems to ignore this annotation although clearly documented, file a bug report?
        # https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#additional-customizations-via-kubernetes-annotations
        # https://github.com/MicrosoftDocs/azure-docs/issues/18204
        "service.beta.kubernetes.io/azure-load-balancer-internal": "false"
      internal:
        enabled: false
    publishService:
      enabled: true
    ingressClass: public
    resources:
      limits:
        cpu: "200m"
        memory: "180Mi"
      requests:
        cpu: "100m"
        memory: "90Mi"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 40
      targetMemoryUtilizationPercentage: 50
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 40
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 40
              periodSeconds: 60
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "ingress"
        additionalLabels:
          release: prometheus
          # suite: "{{ suite }}"
          filia/metrics: prometheus
        metricRelabelings:
          - action: replace
            # replacement: "{{ suite }}"
            targetLabel: suite
        targetLabels:
          - suite
  defaultBackend:
    enabled: false
  ingressClassResource:
    name: "public"

