prometheus:
  namespaceOverride: "monitoring"
  fullnameOverride: "prometheus"
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  prometheus:
    enabled: true
    service:
      type: LoadBalancer
      port: 9090
      targetPort: 9090
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ingress-internal"
        #TODO: Add external dns annotation here
    prometheusSpec:
      portName: http
      resources:
        limits:
          memory: "2500Mi"
        requests:
          memory: "400Mi"
      ruleSelector:
        matchLabels: {}
      serviceMonitorSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: "16Gi"
      externalLabels:
        # cluster: "{{ suite_k8s_namespace }}"
  prometheus-node-exporter:
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
promtail:
  config:
    clients:
      - url: http://default/loki/api/v1/push
    extraVolumeMounts:
      - mountPath: /var/log/journal
        name: journal
        readOnly: true
    extraVolumes:
      - hostPath:
          path: /var/log/journal
        name: journal
    # server:
    #   grpc_server_max_recv_msg_size: 8388608
    #   grpc_server_max_send_msg_size: 8388608
    snippets:
      pipeline_stages:
        - cri: {}
        - json:
            expressions:
              level: level
              request_id: request_id
              time: time
        - labels:
            level:
      extraRelabelConfigs:
        - action: labeldrop
          regex: "(app|container|instance|component|namespace)"
        - action: replace
          # replacement: {{ suite_k8s_namespace }}
          target_label: suite